"""Se elimina suspect y se agrega participant en email

Revision ID: 0126331d417f
Revises: 29becd387a60
Create Date: 2025-04-19 18:36:53.409811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0126331d417f'
down_revision: Union[str, None] = '29becd387a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('participant_id', sa.Integer(), nullable=False))
    op.drop_constraint('emails_suspect_id_fkey', 'emails', type_='foreignkey')
    op.create_foreign_key(None, 'emails', 'participants', ['participant_id'], ['id'])
    op.drop_column('emails', 'suspect_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('suspect_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.create_foreign_key('emails_suspect_id_fkey', 'emails', 'suspects', ['suspect_id'], ['id'])
    op.drop_column('emails', 'participant_id')
    # ### end Alembic commands ###
