"""add to field to email

Revision ID: 29becd387a60
Revises: bb154240113d
Create Date: 2025-04-19 16:37:57.571392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29becd387a60'
down_revision: Union[str, None] = 'bb154240113d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('to', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('emails', sa.Column('provider_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'emails', 'users', ['user_id'], ['id'])
    op.drop_column('emails', 'send_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('send_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_column('emails', 'provider_id')
    op.drop_column('emails', 'user_id')
    op.drop_column('emails', 'to')
    # ### end Alembic commands ###
