"""Add status and score columns

Revision ID: 9e9606023ab3
Revises: e27db3911a72
Create Date: 2025-03-22 15:47:23.489341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9606023ab3'
down_revision: Union[str, None] = 'e27db3911a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect_details', sa.Column('score', sa.Integer(), nullable=False))
    op.add_column('prospects', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospects', 'status')
    op.drop_column('prospect_details', 'score')
    # ### end Alembic commands ###
