"""Add deleted column to prospects

Revision ID: d1237fdb9e3e
Revises: 9e9606023ab3
Create Date: 2025-03-25 11:53:50.455753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1237fdb9e3e'
down_revision: Union[str, None] = '9e9606023ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospects', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospects', 'deleted')
    # ### end Alembic commands ###
